[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "unittest",
    "integrationtest",
]

[tool.isort]
profile = "black"
multi_line_output = 10
lines_between_sections = 0