name: On Pull Request

on:
  pull_request

jobs:
  on_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install black pytest mypy pylint twine build bump2version pytest_mock
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
      - uses: actions/checkout@v2
      - name: install self
        run: pwd & python3 -m pip install .
      - name: Unittests With Pytest
        run: |
          pytest -m unittest
      - name: Integration Tests With Ptest
        run: |
          pytest -m integrationtest
